CREATE OR REPLACE PACKAGE UserManagementPackage AS
  PROCEDURE CreateUser(p_username IN VARCHAR2, p_password IN VARCHAR2);
END UserManagementPackage;
/

CREATE OR REPLACE PACKAGE BODY UserManagementPackage AS
  PROCEDURE CreateUser(p_username IN VARCHAR2, p_password IN VARCHAR2) IS
    V_USER VARCHAR2(100);
  BEGIN
    SELECT USERNAME INTO V_USER FROM ALL_USERS WHERE USERNAME = p_username;
    
    DBMS_OUTPUT.PUT_LINE('USER: ' || p_username || ' already exists');
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      EXECUTE IMMEDIATE 'CREATE USER ' || p_username || ' IDENTIFIED BY ' || p_password;
      EXECUTE IMMEDIATE 'GRANT CONNECT TO ' || p_username;

      -- Additional grants based on user roles
      CASE p_username
        WHEN 'USER_MANAGER' THEN
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_CUSTOMER TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_SAVED_ADDRESSES TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_CUSTOMER TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_SAVED_ADDRESSES TO ' || p_username;
        WHEN 'ORDER_MANAGER' THEN
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ORDERS TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ITEM TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ORDER_TRACKING TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_ORDER TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_ITEM TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_ORDER_AMOUNT TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_ORDER_TRACKING TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.MATCH_DRIVER TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.UPDATE_PAYMENT_STATUS TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_FEEDBACK TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_CUSTOMER TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_DELIVERY_AGENT TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ORDER_HISTORY_LOG TO ' || p_username;
        WHEN 'DELIVERY_AGENT_MANAGER' THEN
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_DELIVERY_AGENT TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_VEHICLE TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_VEHICLE TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT EXECUTE ON KITKY_ADMIN.ADD_DELIVERY_AGENT TO ' || p_username;
        WHEN 'BUSINESS_ANALYST' THEN
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_DRIVER_EARNING TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_CANCELLED_ORDERS TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ORDERS_PLACED_PERDAY TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_TOTAL_CUST_AGENT TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_DRIVER_FEEDBACK_SUMMARY TO ' || p_username;
          EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_AGENT_VEHICLE_ASSIGNMENTS TO ' || p_username;
         
      END CASE;

      DBMS_OUTPUT.PUT_LINE(p_username || ' created successfully');
  END CreateUser;
END UserManagementPackage;
/

/*
DROP USER USER_MANAGER;
DROP USER ORDER_MANAGER;
DROP USER DELIVERY_AGENT_MANAGER;
DROP USER BUSINESS_ANALYST;
*/

BEGIN
  UserManagementPackage.CreateUser('USER_MANAGER', 'UserManager_123');
  UserManagementPackage.CreateUser('ORDER_MANAGER', 'OrderManager_123');
  UserManagementPackage.CreateUser('DELIVERY_AGENT_MANAGER', 'DeliveryAgentManager_123');
  UserManagementPackage.CreateUser('BUSINESS_ANALYST', 'BusinessAnalyst_123');
END;
/
