
-- ORDER 1
EXEC KITKY_ADMIN.ADD_ORDER(5555555555, '123 Collection St', 54321, 'New York', 'New York', 98765, '789 Beach Blvd', 'Ken', 8765432109, 'Bob', 'Handle with care', 3);
EXEC KITKY_ADMIN.ADD_ITEM(1, 'Laptop', 'MEDIUM');
EXEC KITKY_ADMIN.ADD_ITEM(1, 'Camera', 'SMALL');
EXEC KITKY_ADMIN.ADD_ORDER_AMOUNT(1);
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(1,'MATCHING_DRIVER');
EXEC KITKY_ADMIN.MATCH_DRIVER(1,1);
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(1,'DRIVER_MATCHED');
EXEC KITKY_ADMIN.UPDATE_PAYMENT_STATUS(1,'FAILED')
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(1,'CANCELLED');
EXEC KITKY_ADMIN.ADD_FEEDBACK(1,'Payment is not user friendly', 4, 5 );


--ORDER 2
EXEC KITKY_ADMIN.ADD_ORDER(1112223333, '101 Corporate Lane', 11111, 'Massachusetts', 'Boston', 11111, '101 Dimock street', 'king', 4445556666, 'Emily', 'Fragile items',4);
EXEC KITKY_ADMIN.ADD_ITEM(2, 'Printer', 'LARGE');
EXEC KITKY_ADMIN.ADD_ITEM(2, 'Headphones', 'SMALL');
EXEC KITKY_ADMIN.ADD_ORDER_AMOUNT(2);
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(2,'MATCHING_DRIVER');
EXEC KITKY_ADMIN.MATCH_DRIVER(2,2);
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(2,'DRIVER_MATCHED');
EXEC KITKY_ADMIN.UPDATE_PAYMENT_STATUS(2,'SUCCESSFUL')
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(2,'PLACED');
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(2,'PICKED');
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(2,'DELIVERED');
EXEC KITKY_ADMIN.ADD_FEEDBACK(2,'Good and quick service', 3, 3 );


--ORDER 3
EXEC KITKY_ADMIN.ADD_ORDER(4445556666, '555 Pickup Lane', 54321, 'Illinois', 'Chicago', 54321, '456 Business Ave', 'Alice', 9876543210, 'Michael', 'Handle with extra care', 2 );
EXEC KITKY_ADMIN.ADD_ITEM(3, 'Tablet', 'MEDIUM');
EXEC KITKY_ADMIN.ADD_ORDER_AMOUNT(3);
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(3,'MATCHING_DRIVER');
EXEC KITKY_ADMIN.MATCH_DRIVER(3,3);
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(3,'DRIVER_MATCHED');
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(3,'PLACED');
EXEC KITKY_ADMIN.UPDATE_PAYMENT_STATUS(3,'REFUNDED')
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(3,'CANCELLED');
EXEC KITKY_ADMIN.ADD_FEEDBACK(3,'Quick refund,good service', 5, 7 );

--ORDER 4
EXEC KITKY_ADMIN.ADD_ORDER(9990001111, '39 west walnut', 87654, 'Massachusetts', 'Boston', 02115, '123 Main St', 'John', 1234567890, 'Jude', 'Quick delivery requested', 1 );
EXEC KITKY_ADMIN.ADD_ITEM(4, 'Document', 'SMALL');
EXEC KITKY_ADMIN.ADD_ORDER_AMOUNT(4);
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(4,'MATCHING_DRIVER');
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(4,'CANCELLED');
EXEC KITKY_ADMIN.ADD_FEEDBACK(4,'No driver matched after waiting for 15 mins, add more drivers',2,0)

--ORDER 5
EXEC KITKY_ADMIN.ADD_ORDER(4445556666, '321 Friendship St', 11111, 'Florida', 'Nashville', 01234, '789 Speedy St', 'Kane', 2223334444, 'Michael', 'Standard delivery drop in front of door', 5);
EXEC KITKY_ADMIN.ADD_ITEM(5, 'LunchBox', 'SMALL');
EXEC KITKY_ADMIN.ADD_ITEM(5,'Medicine', 'SMALL');
EXEC KITKY_ADMIN.ADD_ORDER_AMOUNT(5);
EXEC KITKY_ADMIN.ADD_ORDER_TRACKING(5,'CANCELLED')
EXEC KITKY_ADMIN.ADD_FEEDBACK(5,'Too costly' ,3, 0)

----------------------------------------------------------------------------------------------------

SELECT * FROM KITKY_ADMIN.V_ORDERS;
SELECT * FROM KITKY_ADMIN.V_ITEM;
SELECT * FROM KITKY_ADMIN.V_ORDER_TRACKING;


