CREATE OR REPLACE TRIGGER SAVE_HISTORY_LOG
BEFORE UPDATE ON ORDERS
FOR EACH ROW
BEGIN
    INSERT INTO ORDER_HISTORY VALUES (
        ORDER_HISTORY_SEQ.NEXTVAL,
        :OLD.ORDER_ID,
        :OLD.AGENT_ID,
        :OLD.CUST_ID,
        :OLD.ORDER_AMOUNT,
        :OLD.TIP_TO_AGENT,
        :OLD.PAYMENT_STATUS,
        :OLD.RATING,
        :OLD.FEEDBACK,
        SYSTIMESTAMP,
        USER
    );
END;
/