
SELECT * FROM KITKY_ADMIN.V_DRIVER_EARNING;
SELECT * FROM KITKY_ADMIN.V_CANCELLED_ORDERS;
SELECT * FROM KITKY_ADMIN.V_ORDERS_PLACED_PERDAY;
SELECT * FROM KITKY_ADMIN.V_TOTAL_CUST_AGENT;
SELECT * FROM KITKY_ADMIN.V_DRIVER_FEEDBACK_SUMMARY;
SELECT * FROM KITKY_ADMIN.V_AGENT_VEHICLE_ASSIGNMENTS;