-- Stored procedure for adding order amount
CREATE OR REPLACE PROCEDURE ADD_ORDER_AMOUNT(PI_ORDER_ID NUMBER)
AS
    INVALID_ORDER_ID EXCEPTION;
    V_ORDER_ID NUMBER;
BEGIN
    SELECT COUNT(ORDER_ID) INTO V_ORDER_ID FROM ORDERS WHERE ORDER_ID = PI_ORDER_ID;
    IF V_ORDER_ID = 0 THEN
        RAISE INVALID_ORDER_ID;
    END IF;

    UPDATE ORDERS 
    SET ORDER_AMOUNT = CALCULATE_ORDER_AMOUNT(PI_ORDER_ID)
    WHERE ORDER_ID = PI_ORDER_ID;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Order amount updated successfully');
EXCEPTION
    WHEN INVALID_ORDER_ID THEN
        DBMS_OUTPUT.PUT_LINE('OrderID does not exist');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END ADD_ORDER_AMOUNT;
/


--EXEC ADD_ORDER_AMOUNT(3);


