SET SERVEROUTPUT ON;


DECLARE
    V_USER VARCHAR(100);
BEGIN
    SELECT USERNAME INTO V_USER FROM ALL_USERS WHERE USERNAME='USER_MANAGER';
    DBMS_OUTPUT.PUT_LINE('USER: USER_MANAGER already exists');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    EXECUTE IMMEDIATE 'CREATE USER USER_MANAGER IDENTIFIED BY UserManager_123';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO USER_MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_CUSTOMER TO USER_MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_SAVED_ADDRESSES TO USER_MANAGER';
    DBMS_OUTPUT.PUT_LINE('USER_MANAGER created successfully');
END;
/


DECLARE
    V_USER VARCHAR(100);
BEGIN
    SELECT USERNAME INTO V_USER FROM ALL_USERS WHERE USERNAME='ORDER_MANAGER';
    DBMS_OUTPUT.PUT_LINE('USER: ORDER_MANAGER already exists');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    EXECUTE IMMEDIATE 'CREATE USER ORDER_MANAGER IDENTIFIED BY OrderManager_123';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO ORDER_MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ORDERS TO ORDER_MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ITEM TO ORDER_MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ORDER_TRACKING TO ORDER_MANAGER';
    DBMS_OUTPUT.PUT_LINE('ORDER_MANAGER created successfully');
END;
/


DECLARE
    V_USER VARCHAR(100);
BEGIN
    SELECT USERNAME INTO V_USER FROM ALL_USERS WHERE USERNAME='DELIVERY_AGENT_MANAGER';
    DBMS_OUTPUT.PUT_LINE('USER: DELIVERY_AGENT_MANAGER already exists');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    EXECUTE IMMEDIATE 'CREATE USER DELIVERY_AGENT_MANAGER IDENTIFIED BY DeliveryAgentManager_123';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO DELIVERY_AGENT_MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_DELIVERY_AGENT TO DELIVERY_AGENT_MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_VEHICLE TO DELIVERY_AGENT_MANAGER';
    DBMS_OUTPUT.PUT_LINE('DELIVERY_AGENT_MANAGER created successfully');
END;
/

DECLARE
    V_USER VARCHAR(100);
BEGIN
    SELECT USERNAME INTO V_USER FROM ALL_USERS WHERE USERNAME='BUSINESS_ANALYST';
    DBMS_OUTPUT.PUT_LINE('USER: BUSINESS_ANALYST already exists');
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    EXECUTE IMMEDIATE 'CREATE USER BUSINESS_ANALYST IDENTIFIED BY BusinessAnalyst_123';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO BUSINESS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_DRIVER_EARNING TO BUSINESS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_CANCELLED_ORDERS TO BUSINESS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_ORDERS_PLACED_PERDAY TO BUSINESS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_TOTAL_CUST_AGENT TO BUSINESS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_DRIVER_FEEDBACK_SUMMARY TO BUSINESS_ANALYST';
    EXECUTE IMMEDIATE 'GRANT SELECT ON KITKY_ADMIN.V_AGENT_VEHICLE_ASSIGNMENTS TO BUSINESS_ANALYST';
    DBMS_OUTPUT.PUT_LINE('BUSINESS_ANALYST created successfully');
END;
/